server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:portal}
    username: ${DB_USER:portal}
    password: ${DB_PASS:portal}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: ${JWT_SECRET:change-me-please}
    expiration: 3600000
  storage:
    path: ${STORAGE_PATH:/data/pdfs}
